{{- if .Values.githubWebhookServer.enabled }}
{{- if .Values.githubWebhookServer.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.githubWebhookServer.secret }}
  {{ $k }}: {{ $v | toString | b64enc }}
{{- end }} 
{{- end }}
{{- end }}
